### ISSUE TITLE
关于业务逻辑与去重表更新操作不在一个原子操作中的问题探讨

### ISSUE THREAD

**Issue by objcoding** [Jaskey/RocketMQDedupListener#1]
大佬，你好，非常感谢你提供的消息幂等处理 Demo！
在阅读你的实现中，我看了下com.github.jaskey.rocketmq.strategy.DedupConsumeStrategy#doHandleMsgAndUpdateStatus 方法，发现业务逻辑和去重表更新操作不在一个原子操作中，如果出现业务逻辑处理成功后没有更新去重表，怎么办？
还是说这个发生的机率很小，是业务允许的范围之内？
就像 RocketMQ 无法保证严格的顺序消息，但普通的顺序消息一般业务能够接收一样？

**Comment by Jaskey** [comment]
你好，可以参考这个博文。为什么不做成原子操作是有客观限制的。

http://jaskey.github.io/blog/2020/06/08/rocketmq-message-dedup/

**Comment by objcoding** [comment]
大概明白你的客观因素了，我说下我的理解：
即使你加了本地事务，也不能保证子过程的幂等（子过程可能不支持回滚操作，比如 RPC 调用），意味着这个事务实际上不是原子性的，因此包裹本地事务并不能解决原子性问题，还会大大降低并发度。
为了解决这个通用的场景，你在去重表加了一个状态，把这个操作进行拆分，这样就能就能推广到更复杂的场景例如：RPC、跨库等。

因此，在极端情况下，即使失败了，但 RocketMQ 依然不会因此而丢消息。（在我看来丢消息比重复消费消息更可怕）

**Comment by Jaskey** [comment]
是的，你的理解很正确。如果业务场景是宁丢勿重。我们去重表的逻辑也可以做一些微调，只是目前不支持这个去重策略。
