### ISSUE TITLE
消息成功消费后的问题

### ISSUE THREAD

**Issue by 872699467** [Jaskey/RocketMQDedupListener#4]
大佬，你好。我看在DedupConcurrentListener类的consumeMessage方法中若消息全部成功消费只是简单了打印下了log。如果像流程图那样更新消息表状态为成功，那样可能在更新消息表的过程中宕机了，那么还是会出现消息重复的问题吧。请问一般如何解决？

**Comment by 872699467** [comment]
找到更新状态的代码了

**Comment by Jaskey** [comment]
消费成功会更新状态，消费失败会删除
